#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace AutoRest.CSharp.Templates.Rest.Client
{

#line 2 "SimpleAuthApiTemplate.cshtml"
using System;

#line default
#line hidden
using System.Collections.Generic;

#line 3 "SimpleAuthApiTemplate.cshtml"
using System.Linq;

#line default
#line hidden
using System.Text;

#line 4 "SimpleAuthApiTemplate.cshtml"
using AutoRest.Core.Utilities;

#line default
#line hidden

#line 5 "SimpleAuthApiTemplate.cshtml"
using AutoRest.Core.Model;

#line default
#line hidden

#line 6 "SimpleAuthApiTemplate.cshtml"
using AutoRest.CSharp.Model;

#line default
#line hidden

#line 7 "SimpleAuthApiTemplate.cshtml"
using AutoRest.CSharp.Templates;

#line default
#line hidden


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "2.6.0.0")]
public partial class SimpleAuthApiTemplate : AutoRest.Core.Template<ApiModel>
{

#line hidden

public override void Execute()
{

#line 9 "SimpleAuthApiTemplate.cshtml"
Write(Header("// "));


#line default
#line hidden
WriteLiteral("\n");


#line 10 "SimpleAuthApiTemplate.cshtml"
Write(EmptyLine);


#line default
#line hidden
WriteLiteral("\nnamespace ");


#line 11 "SimpleAuthApiTemplate.cshtml"
     Write(Settings.Namespace);


#line default
#line hidden
WriteLiteral("\n{\n    using SimpleAuth;\n    using System.Net.Http;\n");


#line 15 "SimpleAuthApiTemplate.cshtml"
 foreach (var usingString in Model.CodeModel.Usings) {


#line default
#line hidden
WriteLiteral("    ");

WriteLiteral("using ");


#line 16 "SimpleAuthApiTemplate.cshtml"
       Write(usingString);


#line default
#line hidden
WriteLiteral(";\n");


#line 17 "SimpleAuthApiTemplate.cshtml"
}


#line default
#line hidden
WriteLiteral("\n");

WriteLiteral("    ");


#line 19 "SimpleAuthApiTemplate.cshtml"
Write(EmptyLine);


#line default
#line hidden
WriteLiteral("\n");


#line 20 "SimpleAuthApiTemplate.cshtml"
    

#line default
#line hidden

#line 20 "SimpleAuthApiTemplate.cshtml"
     if (!string.IsNullOrWhiteSpace(Model.CodeModel.Documentation))
    {


#line default
#line hidden
WriteLiteral("    ");

WriteLiteral("/// <summary>\n");

WriteLiteral("    ");


#line 23 "SimpleAuthApiTemplate.cshtml"
 Write(WrapComment("/// ", Model.CodeModel.Documentation.EscapeXmlComment()));


#line default
#line hidden
WriteLiteral("\n");

WriteLiteral("    ");

WriteLiteral("/// </summary>\n");


#line 25 "SimpleAuthApiTemplate.cshtml"
    }


#line default
#line hidden
WriteLiteral("\n    public partial class ");


#line 27 "SimpleAuthApiTemplate.cshtml"
                    Write(Model.Name);


#line default
#line hidden
WriteLiteral(" : ");


#line 27 "SimpleAuthApiTemplate.cshtml"
                                  Write(Model.ApiSubclass);


#line default
#line hidden
WriteLiteral("\n    {\n\n\n");

WriteLiteral("        ");


#line 31 "SimpleAuthApiTemplate.cshtml"
   Write(Model.BuildConstructor());


#line default
#line hidden
WriteLiteral("\n    \t/// <summary>\n        /// An optional partial-method to perform custom init" +
"ialization.\n        ///</summary>\n        partial void CustomInitialize();\n\n");


#line 37 "SimpleAuthApiTemplate.cshtml"
        

#line default
#line hidden

#line 37 "SimpleAuthApiTemplate.cshtml"
         foreach (var operation in Model.Operations)
        {


#line default
#line hidden
WriteLiteral("        ");

WriteLiteral("/// <summary>\n");

WriteLiteral("        ");

WriteLiteral("/// Gets the ");


#line 40 "SimpleAuthApiTemplate.cshtml"
                   Write(operation.TypeName);


#line default
#line hidden
WriteLiteral(".\n");

WriteLiteral("        ");

WriteLiteral("/// </summary>\n");

WriteLiteral("        ");

WriteLiteral("public virtual ");


#line 42 "SimpleAuthApiTemplate.cshtml"
                     Write(operation.TypeName);


#line default
#line hidden
WriteLiteral("Class ");


#line 42 "SimpleAuthApiTemplate.cshtml"
                                                Write(operation.NameForProperty);


#line default
#line hidden
WriteLiteral(" { get; private set; }\n");


#line 43 "SimpleAuthApiTemplate.cshtml"
        

#line default
#line hidden

#line 43 "SimpleAuthApiTemplate.cshtml"
   Write(EmptyLine);


#line default
#line hidden

#line 43 "SimpleAuthApiTemplate.cshtml"
                  
        }


#line default
#line hidden
WriteLiteral("\n        /// <summary>\n        /// Initializes client properties.\n        /// </s" +
"ummary>\n        private void Initialize()\n        {\n");


#line 51 "SimpleAuthApiTemplate.cshtml"
        

#line default
#line hidden

#line 51 "SimpleAuthApiTemplate.cshtml"
         foreach (var operation in Model.Operations)
        {


#line default
#line hidden
WriteLiteral("            ");

WriteLiteral("this.");


#line 53 "SimpleAuthApiTemplate.cshtml"
               Write(operation.NameForProperty);


#line default
#line hidden
WriteLiteral(" = new ");


#line 53 "SimpleAuthApiTemplate.cshtml"
                                                  Write(operation.TypeName);


#line default
#line hidden
WriteLiteral("Class(this);\n");


#line 54 "SimpleAuthApiTemplate.cshtml"
        }


#line default
#line hidden
WriteLiteral("\n");


#line 56 "SimpleAuthApiTemplate.cshtml"
        

#line default
#line hidden

#line 56 "SimpleAuthApiTemplate.cshtml"
         if (Model.CodeModel.IsCustomBaseUri)
        {


#line default
#line hidden
WriteLiteral("            ");

WriteLiteral("this.BaseAddress = \"");


#line 58 "SimpleAuthApiTemplate.cshtml"
                             Write(Model.CodeModel.BaseUrl);


#line default
#line hidden
WriteLiteral("\";\n");


#line 59 "SimpleAuthApiTemplate.cshtml"
        }
        else
        {


#line default
#line hidden
WriteLiteral("            ");

WriteLiteral("this.BaseAddress = new System.Uri(\"");


#line 62 "SimpleAuthApiTemplate.cshtml"
                                            Write(Model.CodeModel.BaseUrl);


#line default
#line hidden
WriteLiteral("\");\n");


#line 63 "SimpleAuthApiTemplate.cshtml"
        }


#line default
#line hidden
WriteLiteral("\n            CustomInitialize();\n        }\n");

WriteLiteral("        ");


#line 67 "SimpleAuthApiTemplate.cshtml"
   Write(EmptyLine);


#line default
#line hidden
WriteLiteral("\n\n");


#line 69 "SimpleAuthApiTemplate.cshtml"
        

#line default
#line hidden

#line 69 "SimpleAuthApiTemplate.cshtml"
         foreach (MethodCs method in Model.CodeModel.Methods.Where( m => m.Group.IsNullOrEmpty() && (m.HasSecurity(Model.Definition.ApiKey))))
        {


#line default
#line hidden
WriteLiteral("        ");


#line 71 "SimpleAuthApiTemplate.cshtml"
      Write(Include(new SimpleAuthMethodTemplate(), new Tuple<MethodCs,bool>(method,false)));


#line default
#line hidden
WriteLiteral("\n");


#line 72 "SimpleAuthApiTemplate.cshtml"
        

#line default
#line hidden

#line 72 "SimpleAuthApiTemplate.cshtml"
   Write(EmptyLine);


#line default
#line hidden

#line 72 "SimpleAuthApiTemplate.cshtml"
                  


#line default
#line hidden
WriteLiteral("        ");

WriteLiteral("\n");


#line 74 "SimpleAuthApiTemplate.cshtml"
        }


#line default
#line hidden
WriteLiteral("\n");


#line 76 "SimpleAuthApiTemplate.cshtml"
        

#line default
#line hidden

#line 76 "SimpleAuthApiTemplate.cshtml"
         foreach (MethodGroupCs operation in Model.Operations)
        {


#line default
#line hidden
WriteLiteral("        ");


#line 78 "SimpleAuthApiTemplate.cshtml"
      Write(Include(new SimpleAuthApiGroupedCallsTemplate(), new Tuple<ApiModel,MethodGroupCs>(Model,operation)));


#line default
#line hidden
WriteLiteral("\n");


#line 79 "SimpleAuthApiTemplate.cshtml"
        

#line default
#line hidden

#line 79 "SimpleAuthApiTemplate.cshtml"
   Write(EmptyLine);


#line default
#line hidden

#line 79 "SimpleAuthApiTemplate.cshtml"
                  
        }


#line default
#line hidden
WriteLiteral("\n    }\n}");

}
}
}
#pragma warning restore 1591
