#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace AutoRest.CSharp.Templates.Rest.Client
{

#line 2 "SimpleAuthMethodTemplate.cshtml"
using System;

#line default
#line hidden
using System.Collections.Generic;

#line 3 "SimpleAuthMethodTemplate.cshtml"
using System.Linq;

#line default
#line hidden
using System.Text;

#line 4 "SimpleAuthMethodTemplate.cshtml"
using AutoRest.Core.Utilities;

#line default
#line hidden

#line 5 "SimpleAuthMethodTemplate.cshtml"
using AutoRest.CSharp.Model;

#line default
#line hidden

#line 6 "SimpleAuthMethodTemplate.cshtml"
using AutoRest.CSharp.Templates;

#line default
#line hidden


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "2.6.0.0")]
public partial class SimpleAuthMethodTemplate : AutoRest.Core.Template<AutoRest.CSharp.Model.MethodCs>
{

#line hidden

public override void Execute()
{

#line 9 "SimpleAuthMethodTemplate.cshtml"
 if (!string.IsNullOrWhiteSpace(Model.Description) || !string.IsNullOrEmpty(Model.Summary))
{


#line default
#line hidden
WriteLiteral("/// <summary>\n");


#line 12 "SimpleAuthMethodTemplate.cshtml"
Write(WrapComment("/// ", String.IsNullOrEmpty(Model.Summary) ? Model.Description.EscapeXmlComment() : Model.Summary.EscapeXmlComment()));


#line default
#line hidden
WriteLiteral("\n");


#line 13 "SimpleAuthMethodTemplate.cshtml"
    if (!string.IsNullOrEmpty(Model.ExternalDocsUrl))
    {


#line default
#line hidden
WriteLiteral("/// <see href=\"");


#line 15 "SimpleAuthMethodTemplate.cshtml"
            Write(Model.ExternalDocsUrl);


#line default
#line hidden
WriteLiteral("\" />\n");


#line 16 "SimpleAuthMethodTemplate.cshtml"
    }


#line default
#line hidden
WriteLiteral("/// </summary>\n");


#line 18 "SimpleAuthMethodTemplate.cshtml"
}


#line default
#line hidden

#line 19 "SimpleAuthMethodTemplate.cshtml"
 if (!String.IsNullOrEmpty(Model.Description) && !String.IsNullOrEmpty(Model.Summary))
{


#line default
#line hidden
WriteLiteral("/// <remarks>\n");


#line 22 "SimpleAuthMethodTemplate.cshtml"
Write(WrapComment("/// ", Model.Description.EscapeXmlComment()));


#line default
#line hidden
WriteLiteral("\n");

WriteLiteral("/// </remarks>\n");


#line 24 "SimpleAuthMethodTemplate.cshtml"
}


#line default
#line hidden

#line 25 "SimpleAuthMethodTemplate.cshtml"
 foreach (var parameter in Model.LocalParameters)
{


#line default
#line hidden
WriteLiteral("/// <param name=\'");


#line 27 "SimpleAuthMethodTemplate.cshtml"
              Write(parameter.Name);


#line default
#line hidden
WriteLiteral("\'>\n");


#line 28 "SimpleAuthMethodTemplate.cshtml"


#line default
#line hidden

#line 28 "SimpleAuthMethodTemplate.cshtml"
Write(WrapComment("/// ", parameter.Documentation.EscapeXmlComment()));


#line default
#line hidden
WriteLiteral("\n");

WriteLiteral("/// </param>\n");


#line 30 "SimpleAuthMethodTemplate.cshtml"
}


#line default
#line hidden
WriteLiteral("\n");


#line 32 "SimpleAuthMethodTemplate.cshtml"
 if (Model.Deprecated)
{


#line default
#line hidden
WriteLiteral("[System.Obsolete()]\n");


#line 35 "SimpleAuthMethodTemplate.cshtml"
}


#line default
#line hidden
WriteLiteral("public async Task<");


#line 36 "SimpleAuthMethodTemplate.cshtml"
              Write(Model.OperationResponseReturnTypeString);


#line default
#line hidden
WriteLiteral("> ");


#line 36 "SimpleAuthMethodTemplate.cshtml"
                                                          Write(Model.Name);


#line default
#line hidden
WriteLiteral("(");


#line 36 "SimpleAuthMethodTemplate.cshtml"
                                                                        Write(Model.GetAsyncMethodParameterDeclaration(true));


#line default
#line hidden
WriteLiteral(")\n{\n\n}");

}
}
}
#pragma warning restore 1591
