#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace AutoRest.CSharp.Templates.Rest.Client
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

#line 2 "SimpleAuthApiGroupedCallsTemplate.cshtml"
using AutoRest.CSharp.Model;

#line default
#line hidden

#line 3 "SimpleAuthApiGroupedCallsTemplate.cshtml"
using AutoRest.CSharp.Templates;

#line default
#line hidden

#line 4 "SimpleAuthApiGroupedCallsTemplate.cshtml"
using AutoRest.CSharp.Templates.Rest.Client;

#line default
#line hidden


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "2.6.0.0")]
public partial class SimpleAuthApiGroupedCallsTemplate : AutoRest.Core.Template<Tuple<ApiModel,AutoRest.CSharp.Model.MethodGroupCs>>
{

#line hidden

public override void Execute()
{
WriteLiteral("public class ");


#line 7 "SimpleAuthApiGroupedCallsTemplate.cshtml"
         Write(Model.Item2.TypeName);


#line default
#line hidden
WriteLiteral("Class\n{\n");

WriteLiteral("    ");


#line 9 "SimpleAuthApiGroupedCallsTemplate.cshtml"
Write(Model.Item1.Name);


#line default
#line hidden
WriteLiteral(" api;\n    public ");


#line 10 "SimpleAuthApiGroupedCallsTemplate.cshtml"
       Write(Model.Item2.TypeName);


#line default
#line hidden
WriteLiteral("Class(");


#line 10 "SimpleAuthApiGroupedCallsTemplate.cshtml"
                                   Write(Model.Item1.Name);


#line default
#line hidden
WriteLiteral(" api)\n    {\n        this.api = api;\n    }\n\n");


#line 15 "SimpleAuthApiGroupedCallsTemplate.cshtml"
    

#line default
#line hidden

#line 15 "SimpleAuthApiGroupedCallsTemplate.cshtml"
     foreach (MethodCs method in Model.Item2.GetMethods(Model.Item1.Definition)) 
    {


#line default
#line hidden
WriteLiteral("    ");


#line 17 "SimpleAuthApiGroupedCallsTemplate.cshtml"
  Write(Include(new SimpleAuthMethodTemplate(), new Tuple<MethodCs,bool>(method,true)));


#line default
#line hidden
WriteLiteral("\n");


#line 18 "SimpleAuthApiGroupedCallsTemplate.cshtml"
    

#line default
#line hidden

#line 18 "SimpleAuthApiGroupedCallsTemplate.cshtml"
Write(EmptyLine);


#line default
#line hidden

#line 18 "SimpleAuthApiGroupedCallsTemplate.cshtml"
              


#line default
#line hidden
WriteLiteral("    ");

WriteLiteral("\n");


#line 20 "SimpleAuthApiGroupedCallsTemplate.cshtml"
    }


#line default
#line hidden
WriteLiteral("\n}\n");

}
}
}
#pragma warning restore 1591
