// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace SimpleSwaggerGenerator.AutoRest.modeler.Properties {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SimpleSwaggerGenerator.AutoRest.modeler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string CircularBaseSchemaSet {
            get {
                return ResourceManager.GetString("CircularBaseSchemaSet", resourceCulture);
            }
        }
        
        internal static string CircularReference {
            get {
                return ResourceManager.GetString("CircularReference", resourceCulture);
            }
        }
        
        internal static string DefinitionDoesNotExist {
            get {
                return ResourceManager.GetString("DefinitionDoesNotExist", resourceCulture);
            }
        }
        
        internal static string DuplicateOperationIdException {
            get {
                return ResourceManager.GetString("DuplicateOperationIdException", resourceCulture);
            }
        }
        
        internal static string ErrorParsingSpec {
            get {
                return ResourceManager.GetString("ErrorParsingSpec", resourceCulture);
            }
        }
        
        internal static string ExceededMaximumReferenceDepth {
            get {
                return ResourceManager.GetString("ExceededMaximumReferenceDepth", resourceCulture);
            }
        }
        
        internal static string GeneratingClient {
            get {
                return ResourceManager.GetString("GeneratingClient", resourceCulture);
            }
        }
        
        internal static string IncompatibleTypesInBaseSchema {
            get {
                return ResourceManager.GetString("IncompatibleTypesInBaseSchema", resourceCulture);
            }
        }
        
        internal static string IncompatibleTypesInSchemaComposition {
            get {
                return ResourceManager.GetString("IncompatibleTypesInSchemaComposition", resourceCulture);
            }
        }
        
        internal static string InfoSectionMissing {
            get {
                return ResourceManager.GetString("InfoSectionMissing", resourceCulture);
            }
        }
        
        internal static string InputRequired {
            get {
                return ResourceManager.GetString("InputRequired", resourceCulture);
            }
        }
        
        internal static string InvalidAncestors {
            get {
                return ResourceManager.GetString("InvalidAncestors", resourceCulture);
            }
        }
        
        internal static string InvalidCollectionFormat {
            get {
                return ResourceManager.GetString("InvalidCollectionFormat", resourceCulture);
            }
        }
        
        internal static string InvalidTypeExtendsWithAllOf {
            get {
                return ResourceManager.GetString("InvalidTypeExtendsWithAllOf", resourceCulture);
            }
        }
        
        internal static string InvalidTypeInSwaggerSchema {
            get {
                return ResourceManager.GetString("InvalidTypeInSwaggerSchema", resourceCulture);
            }
        }
        
        internal static string MultiCollectionFormatNotSupported {
            get {
                return ResourceManager.GetString("MultiCollectionFormatNotSupported", resourceCulture);
            }
        }
        
        internal static string NoProduceOperationWithBody {
            get {
                return ResourceManager.GetString("NoProduceOperationWithBody", resourceCulture);
            }
        }
        
        internal static string OperationIdMissing {
            get {
                return ResourceManager.GetString("OperationIdMissing", resourceCulture);
            }
        }
        
        internal static string OptionsNotSupported {
            get {
                return ResourceManager.GetString("OptionsNotSupported", resourceCulture);
            }
        }
        
        internal static string ParsingSwagger {
            get {
                return ResourceManager.GetString("ParsingSwagger", resourceCulture);
            }
        }
        
        internal static string ReadOnlyNotRequired {
            get {
                return ResourceManager.GetString("ReadOnlyNotRequired", resourceCulture);
            }
        }
        
        internal static string ReferenceDoesNotExist {
            get {
                return ResourceManager.GetString("ReferenceDoesNotExist", resourceCulture);
            }
        }
        
        internal static string TitleMissing {
            get {
                return ResourceManager.GetString("TitleMissing", resourceCulture);
            }
        }
        
        internal static string UnknownSwaggerVersion {
            get {
                return ResourceManager.GetString("UnknownSwaggerVersion", resourceCulture);
            }
        }
        
        internal static string UnsupportedMimeTypeForResponseBody {
            get {
                return ResourceManager.GetString("UnsupportedMimeTypeForResponseBody", resourceCulture);
            }
        }
    }
}
