// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace SimpleSwaggerGenerator.AutoRest.extensions.Properties {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SimpleSwaggerGenerator.AutoRest.extensions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string HeadMethodInvalidResponses {
            get {
                return ResourceManager.GetString("HeadMethodInvalidResponses", resourceCulture);
            }
        }
        
        internal static string InvalidExtensionProperty {
            get {
                return ResourceManager.GetString("InvalidExtensionProperty", resourceCulture);
            }
        }
        
        internal static string MissingProperties {
            get {
                return ResourceManager.GetString("MissingProperties", resourceCulture);
            }
        }
        
        internal static string ODataEmpty {
            get {
                return ResourceManager.GetString("ODataEmpty", resourceCulture);
            }
        }
        
        internal static string ODataFilterMissing {
            get {
                return ResourceManager.GetString("ODataFilterMissing", resourceCulture);
            }
        }
        
        internal static string ODataInvalidReferance {
            get {
                return ResourceManager.GetString("ODataInvalidReferance", resourceCulture);
            }
        }
        
        internal static string ResourcePropertyMismatch {
            get {
                return ResourceManager.GetString("ResourcePropertyMismatch", resourceCulture);
            }
        }
    }
}
