// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace SimpleSwaggerGenerator.AutoRest.core.Properties {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AutoRest.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AutoRestCore {
            get {
                return ResourceManager.GetString("AutoRestCore", resourceCulture);
            }
        }
        
        internal static string CodeGenerationFailed {
            get {
                return ResourceManager.GetString("CodeGenerationFailed", resourceCulture);
            }
        }
        
        internal static string CodeGenSettingsFileInvalid {
            get {
                return ResourceManager.GetString("CodeGenSettingsFileInvalid", resourceCulture);
            }
        }
        
        internal static string CommentString {
            get {
                return ResourceManager.GetString("CommentString", resourceCulture);
            }
        }
        
        internal static string ConfigurationFileNotFound {
            get {
                return ResourceManager.GetString("ConfigurationFileNotFound", resourceCulture);
            }
        }
        
        internal static string DirectoryNotExist {
            get {
                return ResourceManager.GetString("DirectoryNotExist", resourceCulture);
            }
        }
        
        internal static string EntityConflictTitleMessage {
            get {
                return ResourceManager.GetString("EntityConflictTitleMessage", resourceCulture);
            }
        }
        
        internal static string ErrorGeneratingClientModel {
            get {
                return ResourceManager.GetString("ErrorGeneratingClientModel", resourceCulture);
            }
        }
        
        internal static string ErrorLoadingAssembly {
            get {
                return ResourceManager.GetString("ErrorLoadingAssembly", resourceCulture);
            }
        }
        
        internal static string ErrorParsingConfig {
            get {
                return ResourceManager.GetString("ErrorParsingConfig", resourceCulture);
            }
        }
        
        internal static string ErrorSavingGeneratedCode {
            get {
                return ResourceManager.GetString("ErrorSavingGeneratedCode", resourceCulture);
            }
        }
        
        internal static string ExtensionNotFound {
            get {
                return ResourceManager.GetString("ExtensionNotFound", resourceCulture);
            }
        }
        
        internal static string GeneratorInitialized {
            get {
                return ResourceManager.GetString("GeneratorInitialized", resourceCulture);
            }
        }
        
        internal static string InitializingCodeGenerator {
            get {
                return ResourceManager.GetString("InitializingCodeGenerator", resourceCulture);
            }
        }
        
        internal static string InitializingModeler {
            get {
                return ResourceManager.GetString("InitializingModeler", resourceCulture);
            }
        }
        
        internal static string InvalidIdentifierName {
            get {
                return ResourceManager.GetString("InvalidIdentifierName", resourceCulture);
            }
        }
        
        internal static string LanguageDoesNotSupportSingleFileGeneration {
            get {
                return ResourceManager.GetString("LanguageDoesNotSupportSingleFileGeneration", resourceCulture);
            }
        }
        
        internal static string ModelerInitialized {
            get {
                return ResourceManager.GetString("ModelerInitialized", resourceCulture);
            }
        }
        
        internal static string NamespaceConflictReasonMessage {
            get {
                return ResourceManager.GetString("NamespaceConflictReasonMessage", resourceCulture);
            }
        }
        
        internal static string NamingConflictsSuggestion {
            get {
                return ResourceManager.GetString("NamingConflictsSuggestion", resourceCulture);
            }
        }
        
        internal static string ParameterIsNotValid {
            get {
                return ResourceManager.GetString("ParameterIsNotValid", resourceCulture);
            }
        }
        
        internal static string ParameterValueIsMissing {
            get {
                return ResourceManager.GetString("ParameterValueIsMissing", resourceCulture);
            }
        }
        
        internal static string ParameterValueIsNotValid {
            get {
                return ResourceManager.GetString("ParameterValueIsNotValid", resourceCulture);
            }
        }
        
        internal static string TypeShouldBeAssemblyQualified {
            get {
                return ResourceManager.GetString("TypeShouldBeAssemblyQualified", resourceCulture);
            }
        }
        
        internal static string AnonymousTypesDiscouraged {
            get {
                return ResourceManager.GetString("AnonymousTypesDiscouraged", resourceCulture);
            }
        }
        
        internal static string MsdnReferencesDiscouraged {
            get {
                return ResourceManager.GetString("MsdnReferencesDiscouraged", resourceCulture);
            }
        }
        
        internal static string APIVersionFormatIsNotValid {
            get {
                return ResourceManager.GetString("APIVersionFormatIsNotValid", resourceCulture);
            }
        }
        
        internal static string HttpVerbIsNotValid {
            get {
                return ResourceManager.GetString("HttpVerbIsNotValid", resourceCulture);
            }
        }
        
        internal static string ResourceModelIsNotValid {
            get {
                return ResourceManager.GetString("ResourceModelIsNotValid", resourceCulture);
            }
        }
        
        internal static string ResourceIsMsResourceNotValid {
            get {
                return ResourceManager.GetString("ResourceIsMsResourceNotValid", resourceCulture);
            }
        }
        
        internal static string XmsClientNameInValid {
            get {
                return ResourceManager.GetString("XmsClientNameInValid", resourceCulture);
            }
        }
        
        internal static string DeleteMustHaveEmptyRequestBody {
            get {
                return ResourceManager.GetString("DeleteMustHaveEmptyRequestBody", resourceCulture);
            }
        }
        
        internal static string SkuModelIsNotValid {
            get {
                return ResourceManager.GetString("SkuModelIsNotValid", resourceCulture);
            }
        }
        
        internal static string PutGetPatchResponseInvalid {
            get {
                return ResourceManager.GetString("PutGetPatchResponseInvalid", resourceCulture);
            }
        }
        
        internal static string OperationsAPINotImplemented {
            get {
                return ResourceManager.GetString("OperationsAPINotImplemented", resourceCulture);
            }
        }
        
        internal static string TrackedResourceIsNotValid {
            get {
                return ResourceManager.GetString("TrackedResourceIsNotValid", resourceCulture);
            }
        }
        
        internal static string BodyMustHaveSchema {
            get {
                return ResourceManager.GetString("BodyMustHaveSchema", resourceCulture);
            }
        }
        
        internal static string BodyWithType {
            get {
                return ResourceManager.GetString("BodyWithType", resourceCulture);
            }
        }
        
        internal static string ConflictingRef {
            get {
                return ResourceManager.GetString("ConflictingRef", resourceCulture);
            }
        }
        
        internal static string EmptyClientName {
            get {
                return ResourceManager.GetString("EmptyClientName", resourceCulture);
            }
        }
        
        internal static string HeaderShouldHaveClientName {
            get {
                return ResourceManager.GetString("HeaderShouldHaveClientName", resourceCulture);
            }
        }
        
        internal static string InvalidDefault {
            get {
                return ResourceManager.GetString("InvalidDefault", resourceCulture);
            }
        }
        
        internal static string InvalidSchemaParameter {
            get {
                return ResourceManager.GetString("InvalidSchemaParameter", resourceCulture);
            }
        }
        
        internal static string UnknownFormat {
            get {
                return ResourceManager.GetString("UnknownFormat", resourceCulture);
            }
        }
        
        internal static string MissingDescription {
            get {
                return ResourceManager.GetString("MissingDescription", resourceCulture);
            }
        }
        
        internal static string MissingRequiredProperty {
            get {
                return ResourceManager.GetString("MissingRequiredProperty", resourceCulture);
            }
        }
        
        internal static string NoDefinitionForPathParameter {
            get {
                return ResourceManager.GetString("NoDefinitionForPathParameter", resourceCulture);
            }
        }
        
        internal static string NoResponses {
            get {
                return ResourceManager.GetString("NoResponses", resourceCulture);
            }
        }
        
        internal static string OnlyOneUnderscoreAllowedInOperationId {
            get {
                return ResourceManager.GetString("OnlyOneUnderscoreAllowedInOperationId", resourceCulture);
            }
        }
        
        internal static string OperationIdMissing {
            get {
                return ResourceManager.GetString("OperationIdMissing", resourceCulture);
            }
        }
        
        internal static string TooManyBodyParameters {
            get {
                return ResourceManager.GetString("TooManyBodyParameters", resourceCulture);
            }
        }
        
        internal static string CodeGenerationError {
            get {
                return ResourceManager.GetString("CodeGenerationError", resourceCulture);
            }
        }
        
        internal static string XMSPathBaseNotInPaths {
            get {
                return ResourceManager.GetString("XMSPathBaseNotInPaths", resourceCulture);
            }
        }
        
        internal static string DescriptionNotDescriptive {
            get {
                return ResourceManager.GetString("DescriptionNotDescriptive", resourceCulture);
            }
        }
        
        internal static string OperationIdNounInVerb {
            get {
                return ResourceManager.GetString("OperationIdNounInVerb", resourceCulture);
            }
        }
        
        internal static string InvalidConstraint {
            get {
                return ResourceManager.GetString("InvalidConstraint", resourceCulture);
            }
        }
        
        internal static string NonAppJsonTypeNotSupported {
            get {
                return ResourceManager.GetString("NonAppJsonTypeNotSupported", resourceCulture);
            }
        }
        
        internal static string SupportedSchemesWarningMessage {
            get {
                return ResourceManager.GetString("SupportedSchemesWarningMessage", resourceCulture);
            }
        }
        
        internal static string OperationParametersNotAllowedMessage {
            get {
                return ResourceManager.GetString("OperationParametersNotAllowedMessage", resourceCulture);
            }
        }
        
        internal static string ServiceDefinitionParametersMissingMessage {
            get {
                return ResourceManager.GetString("ServiceDefinitionParametersMissingMessage", resourceCulture);
            }
        }
        
        internal static string UniqueResourcePathsWarning {
            get {
                return ResourceManager.GetString("UniqueResourcePathsWarning", resourceCulture);
            }
        }
        
        internal static string PathCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("PathCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        internal static string GuidUsageNotRecommended {
            get {
                return ResourceManager.GetString("GuidUsageNotRecommended", resourceCulture);
            }
        }
        
        internal static string OperationNameNotValid {
            get {
                return ResourceManager.GetString("OperationNameNotValid", resourceCulture);
            }
        }
        
        internal static string LongRunningResponseNotValid {
            get {
                return ResourceManager.GetString("LongRunningResponseNotValid", resourceCulture);
            }
        }
        
        internal static string InvalidMutabilityValues {
            get {
                return ResourceManager.GetString("InvalidMutabilityValues", resourceCulture);
            }
        }
        
        internal static string InvalidMutabilityValueForReadOnly {
            get {
                return ResourceManager.GetString("InvalidMutabilityValueForReadOnly", resourceCulture);
            }
        }
    }
}
