#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace AutoRest.CSharp.Templates.Rest.Common
{
using System;
using System.Collections.Generic;
using System.Linq;

#line 2 "ExtensionsTemplate.cshtml"
using System.Text;

#line default
#line hidden

#line 3 "ExtensionsTemplate.cshtml"
using AutoRest.CSharp.Model;

#line default
#line hidden

#line 4 "ExtensionsTemplate.cshtml"
using AutoRest.CSharp.Templates;

#line default
#line hidden


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "2.6.0.0")]
public partial class ExtensionsTemplate : AutoRest.Core.Template<AutoRest.CSharp.Model.MethodGroupCs>
{

#line hidden

public override void Execute()
{

#line 6 "ExtensionsTemplate.cshtml"
Write(Header("// "));


#line default
#line hidden
WriteLiteral("\n");


#line 7 "ExtensionsTemplate.cshtml"
Write(EmptyLine);


#line default
#line hidden
WriteLiteral("\nnamespace ");


#line 8 "ExtensionsTemplate.cshtml"
     Write(Settings.Namespace);


#line default
#line hidden
WriteLiteral("\n{\n");


#line 10 "ExtensionsTemplate.cshtml"
 foreach (var usingString in Model.Usings) {


#line default
#line hidden
WriteLiteral("    ");

WriteLiteral("using ");


#line 11 "ExtensionsTemplate.cshtml"
       Write(usingString);


#line default
#line hidden
WriteLiteral(";\n");


#line 12 "ExtensionsTemplate.cshtml"
}


#line default
#line hidden

#line 13 "ExtensionsTemplate.cshtml"
Write(EmptyLine);


#line default
#line hidden
WriteLiteral("\n    /// <summary>\n    /// Extension methods for ");


#line 15 "ExtensionsTemplate.cshtml"
                          Write(Model.ExtensionTypeName);


#line default
#line hidden
WriteLiteral(".\n    /// </summary>\n    public static partial class ");


#line 17 "ExtensionsTemplate.cshtml"
                            Write(Model.ExtensionTypeName);


#line default
#line hidden
WriteLiteral("Extensions\n    {\n");


#line 19 "ExtensionsTemplate.cshtml"
        

#line default
#line hidden

#line 19 "ExtensionsTemplate.cshtml"
         foreach (MethodCs method in Model.Methods)
        {


#line default
#line hidden
WriteLiteral("            ");


#line 21 "ExtensionsTemplate.cshtml"
          Write(Include(new ExtensionMethodTemplate(), method));


#line default
#line hidden
WriteLiteral("\n");


#line 22 "ExtensionsTemplate.cshtml"
            

#line default
#line hidden

#line 22 "ExtensionsTemplate.cshtml"
       Write(EmptyLine);


#line default
#line hidden

#line 22 "ExtensionsTemplate.cshtml"
                       
        }


#line default
#line hidden
WriteLiteral("    }\n}\n");

}
}
}
#pragma warning restore 1591
